const translations = {
  pt: {
    common: { system: "Sistema", product: "Seu Produto", logo: "Logo", back: "Voltar", month: "mês", rights: "Todos os direitos reservados.", required: "Obrigatório", invalidEmail: "E-mail inválido" },
    banner: { defaultSubtitle: "Use este banner para divulgar planos, campanhas, novidades, diferenciais do produto ou qualquer comunicação visual forte da sua empresa.", badge1: "Banner promocional", badge2: "Divulgação da marca", badge3: "Campanhas e ofertas", fallbackTitle: "Sua marca merece uma entrada forte, bonita e profissional.", loginFallback: "Configure um banner institucional ou promocional para transformar a tela de login em uma vitrine do seu produto.", signupFallback: "Configure um banner institucional ou promocional para transformar a tela de cadastro em uma vitrine do seu produto." },
    login: { title: "Acessar painel", subtitle: "Entre com suas credenciais para acessar o sistema com segurança.", tab: "Entrar", signupTab: "Cadastro", email: "E-mail", emailPlaceholder: "Digite seu e-mail", password: "Senha", passwordPlaceholder: "Digite sua senha", forgot: "Esqueci minha senha", submit: "Entrar", secure: "Ambiente seguro", support: "Suporte centralizado", whatsappAria: "Contato via WhatsApp", whatsappTitle: "Fale conosco no WhatsApp", unconfirmedTitle: "E-mail ainda não confirmado", unconfirmedText: "Encontramos sua conta, mas o acesso só será liberado após a confirmação do código enviado para {{email}}.", codeLabel: "Código de confirmação", codePlaceholder: "Digite o código recebido", confirmCode: "Confirmar código", resending: "Reenviando...", resendCode: "Reenviar código", emailRequiredResend: "Informe seu e-mail para reenviar o código.", codeResent: "Código reenviado com sucesso para o seu e-mail.", emailRequired: "Informe seu e-mail.", codeRequired: "Digite o código recebido no e-mail.", emailConfirmed: "E-mail confirmado com sucesso.", emailUnconfirmed: "Seu e-mail ainda não foi confirmado." },
    signup: { pageTitle: "Cadastro", title: "Criar conta", subtitle: "Escolha um plano e finalize seu cadastro para começar a usar o sistema.", choosePlan: "Escolha seu plano", choosePlanSubtitle: "Selecione a opção ideal para a sua empresa.", loadingPlans: "Carregando planos...", noPlans: "Nenhum plano disponível no momento.", ideal: "Ideal para sua empresa", usersConnections: "Até {{users}} usuários · Até {{connections}} conexões", continue: "Continuar", haveAccount: "Já tem uma conta?", enter: "Entrar", fillData: "Preencha seus dados", fillDataSubtitle: "Informe os dados da sua empresa para concluir o cadastro.", selectedPlan: "Plano selecionado", namePlaceholder: "Digite seu nome", companyPlaceholder: "Nome da empresa", document: "CPF / CNPJ / Documento", documentPlaceholder: "Digite o documento", phonePlaceholder: "Digite seu telefone", passwordPlaceholder: "Crie uma senha", create: "Criar conta", confirmEmail: "Confirmar e-mail", confirmEmailText: "Enviamos um código de confirmação para {{email}}. Digite o código abaixo para liberar seu acesso.", createdPending: "Conta criada com sucesso. Falta apenas confirmar o e-mail.", verificationCode: "Código de verificação", alreadyConfirmed: "Já confirmou seu e-mail?", secure: "Cadastro seguro", simpleActivation: "Ativação simplificada", documentValid: "Documento válido!", companyValid: "CNPJ válido! Nome preenchido automaticamente.", documentInvalid: "Documento inválido.", documentError: "Erro ao validar documento.", created: "Cadastro realizado com sucesso. Enviamos um código para o seu e-mail.", emailMissingConfirm: "E-mail não encontrado para confirmação.", verificationRequired: "Digite o código de verificação.", verified: "E-mail confirmado com sucesso. Agora você já pode entrar.", emailMissingResend: "E-mail não encontrado para reenvio.", codeResent: "Código reenviado com sucesso.", features: { campaigns: "Campanhas", schedules: "Agendamentos", internalChat: "Chat Interno", externalApi: "API Externa", integrations: "Integrações" } },
    forgot: { pageTitle: "Esqueci minha senha", badge: "Redefinição de acesso", title: "Esqueceu sua senha?", subtitle: "Digite seu e-mail abaixo para receber o link de redefinição e recuperar o acesso à sua conta.", email: "E-mail", sending: "Enviando link...", submit: "Enviar link de redefinição", back: "Voltar para o login", error: "Não foi possível processar sua solicitação.", success: "Se o e-mail estiver cadastrado, você receberá o link de redefinição." },
    reset: { pageTitle: "Redefinir senha", title: "Redefinir senha", subtitle: "Informe sua nova senha.", newPassword: "Nova senha", confirmPassword: "Confirmar nova senha", saving: "Salvando...", submit: "Salvar nova senha", back: "Voltar ao login", invalidToken: "Token inválido.", shortPassword: "A senha deve ter pelo menos 6 caracteres.", mismatch: "As senhas não conferem.", invalidLink: "Link inválido ou expirado.", success: "Senha redefinida com sucesso." }
  },
  en: {
    common: { system: "System", product: "Your Product", logo: "Logo", back: "Back", month: "month", rights: "All rights reserved.", required: "Required", invalidEmail: "Invalid email" },
    banner: { defaultSubtitle: "Use this banner to promote plans, campaigns, news, product benefits, or any strong visual communication from your company.", badge1: "Promotional banner", badge2: "Brand promotion", badge3: "Campaigns and offers", fallbackTitle: "Your brand deserves a strong, beautiful, professional entrance.", loginFallback: "Configure an institutional or promotional banner to turn the login screen into a showcase for your product.", signupFallback: "Configure an institutional or promotional banner to turn the sign-up screen into a showcase for your product." },
    login: { title: "Access dashboard", subtitle: "Enter your credentials to securely access the system.", tab: "Sign in", signupTab: "Sign up", email: "Email", emailPlaceholder: "Enter your email", password: "Password", passwordPlaceholder: "Enter your password", forgot: "Forgot my password", submit: "Sign in", secure: "Secure environment", support: "Centralized support", whatsappAria: "Contact via WhatsApp", whatsappTitle: "Contact us on WhatsApp", unconfirmedTitle: "Email not yet confirmed", unconfirmedText: "We found your account, but access will only be released after confirming the code sent to {{email}}.", codeLabel: "Confirmation code", codePlaceholder: "Enter the code you received", confirmCode: "Confirm code", resending: "Resending...", resendCode: "Resend code", emailRequiredResend: "Enter your email to resend the code.", codeResent: "Code successfully resent to your email.", emailRequired: "Enter your email.", codeRequired: "Enter the code received by email.", emailConfirmed: "Email successfully confirmed.", emailUnconfirmed: "Your email has not been confirmed yet." },
    signup: { pageTitle: "Sign up", title: "Create account", subtitle: "Choose a plan and complete your registration to start using the system.", choosePlan: "Choose your plan", choosePlanSubtitle: "Select the best option for your company.", loadingPlans: "Loading plans...", noPlans: "No plans are currently available.", ideal: "Ideal for your company", usersConnections: "Up to {{users}} users · Up to {{connections}} connections", continue: "Continue", haveAccount: "Already have an account?", enter: "Sign in", fillData: "Enter your details", fillDataSubtitle: "Enter your company details to complete registration.", selectedPlan: "Selected plan", namePlaceholder: "Enter your name", companyPlaceholder: "Company name", document: "Tax ID / Document", documentPlaceholder: "Enter the document", phonePlaceholder: "Enter your phone number", passwordPlaceholder: "Create a password", create: "Create account", confirmEmail: "Confirm email", confirmEmailText: "We sent a confirmation code to {{email}}. Enter it below to release your access.", createdPending: "Account successfully created. Just confirm your email.", verificationCode: "Verification code", alreadyConfirmed: "Already confirmed your email?", secure: "Secure registration", simpleActivation: "Simple activation", documentValid: "Valid document!", companyValid: "Valid company ID! Company name filled in automatically.", documentInvalid: "Invalid document.", documentError: "Error validating document.", created: "Registration completed. We sent a code to your email.", emailMissingConfirm: "Email not found for confirmation.", verificationRequired: "Enter the verification code.", verified: "Email confirmed. You can now sign in.", emailMissingResend: "Email not found for resending.", codeResent: "Code successfully resent.", features: { campaigns: "Campaigns", schedules: "Schedules", internalChat: "Internal Chat", externalApi: "External API", integrations: "Integrations" } },
    forgot: { pageTitle: "Forgot my password", badge: "Access recovery", title: "Forgot your password?", subtitle: "Enter your email below to receive the reset link and recover access to your account.", email: "Email", sending: "Sending link...", submit: "Send reset link", back: "Back to login", error: "We could not process your request.", success: "If the email is registered, you will receive the reset link." },
    reset: { pageTitle: "Reset password", title: "Reset password", subtitle: "Enter your new password.", newPassword: "New password", confirmPassword: "Confirm new password", saving: "Saving...", submit: "Save new password", back: "Back to login", invalidToken: "Invalid token.", shortPassword: "The password must be at least 6 characters long.", mismatch: "Passwords do not match.", invalidLink: "Invalid or expired link.", success: "Password successfully reset." }
  },
  es: {
    common: { system: "Sistema", product: "Tu Producto", logo: "Logo", back: "Volver", month: "mes", rights: "Todos los derechos reservados.", required: "Obligatorio", invalidEmail: "Correo electrónico inválido" },
    banner: { defaultSubtitle: "Usa este banner para divulgar planes, campañas, novedades, beneficios del producto o cualquier comunicación visual destacada de tu empresa.", badge1: "Banner promocional", badge2: "Divulgación de la marca", badge3: "Campañas y ofertas", fallbackTitle: "Tu marca merece una entrada fuerte, bonita y profesional.", loginFallback: "Configura un banner institucional o promocional para transformar la pantalla de acceso en una vitrina de tu producto.", signupFallback: "Configura un banner institucional o promocional para transformar la pantalla de registro en una vitrina de tu producto." },
    login: { title: "Acceder al panel", subtitle: "Ingresa tus credenciales para acceder al sistema de forma segura.", tab: "Ingresar", signupTab: "Registro", email: "Correo electrónico", emailPlaceholder: "Ingresa tu correo electrónico", password: "Contraseña", passwordPlaceholder: "Ingresa tu contraseña", forgot: "Olvidé mi contraseña", submit: "Ingresar", secure: "Entorno seguro", support: "Soporte centralizado", whatsappAria: "Contacto por WhatsApp", whatsappTitle: "Habla con nosotros por WhatsApp", unconfirmedTitle: "Correo aún no confirmado", unconfirmedText: "Encontramos tu cuenta, pero el acceso solo se habilitará después de confirmar el código enviado a {{email}}.", codeLabel: "Código de confirmación", codePlaceholder: "Ingresa el código recibido", confirmCode: "Confirmar código", resending: "Reenviando...", resendCode: "Reenviar código", emailRequiredResend: "Ingresa tu correo para reenviar el código.", codeResent: "Código reenviado correctamente a tu correo.", emailRequired: "Ingresa tu correo electrónico.", codeRequired: "Ingresa el código recibido por correo.", emailConfirmed: "Correo confirmado correctamente.", emailUnconfirmed: "Tu correo todavía no ha sido confirmado." },
    signup: { pageTitle: "Registro", title: "Crear cuenta", subtitle: "Elige un plan y completa tu registro para comenzar a usar el sistema.", choosePlan: "Elige tu plan", choosePlanSubtitle: "Selecciona la opción ideal para tu empresa.", loadingPlans: "Cargando planes...", noPlans: "No hay planes disponibles en este momento.", ideal: "Ideal para tu empresa", usersConnections: "Hasta {{users}} usuarios · Hasta {{connections}} conexiones", continue: "Continuar", haveAccount: "¿Ya tienes una cuenta?", enter: "Ingresar", fillData: "Completa tus datos", fillDataSubtitle: "Ingresa los datos de tu empresa para completar el registro.", selectedPlan: "Plan seleccionado", namePlaceholder: "Ingresa tu nombre", companyPlaceholder: "Nombre de la empresa", document: "NIF / Documento", documentPlaceholder: "Ingresa el documento", phonePlaceholder: "Ingresa tu teléfono", passwordPlaceholder: "Crea una contraseña", create: "Crear cuenta", confirmEmail: "Confirmar correo", confirmEmailText: "Enviamos un código de confirmación a {{email}}. Ingrésalo abajo para habilitar tu acceso.", createdPending: "Cuenta creada correctamente. Solo falta confirmar el correo.", verificationCode: "Código de verificación", alreadyConfirmed: "¿Ya confirmaste tu correo?", secure: "Registro seguro", simpleActivation: "Activación simplificada", documentValid: "¡Documento válido!", companyValid: "¡Documento empresarial válido! Nombre completado automáticamente.", documentInvalid: "Documento inválido.", documentError: "Error al validar el documento.", created: "Registro completado. Enviamos un código a tu correo.", emailMissingConfirm: "No se encontró el correo para confirmarlo.", verificationRequired: "Ingresa el código de verificación.", verified: "Correo confirmado. Ya puedes ingresar.", emailMissingResend: "No se encontró el correo para reenviar el código.", codeResent: "Código reenviado correctamente.", features: { campaigns: "Campañas", schedules: "Programaciones", internalChat: "Chat Interno", externalApi: "API Externa", integrations: "Integraciones" } },
    forgot: { pageTitle: "Olvidé mi contraseña", badge: "Restablecimiento de acceso", title: "¿Olvidaste tu contraseña?", subtitle: "Ingresa tu correo abajo para recibir el enlace de restablecimiento y recuperar el acceso a tu cuenta.", email: "Correo electrónico", sending: "Enviando enlace...", submit: "Enviar enlace de restablecimiento", back: "Volver al acceso", error: "No fue posible procesar tu solicitud.", success: "Si el correo está registrado, recibirás el enlace de restablecimiento." },
    reset: { pageTitle: "Restablecer contraseña", title: "Restablecer contraseña", subtitle: "Ingresa tu nueva contraseña.", newPassword: "Nueva contraseña", confirmPassword: "Confirmar nueva contraseña", saving: "Guardando...", submit: "Guardar nueva contraseña", back: "Volver al acceso", invalidToken: "Token inválido.", shortPassword: "La contraseña debe tener al menos 6 caracteres.", mismatch: "Las contraseñas no coinciden.", invalidLink: "Enlace inválido o vencido.", success: "Contraseña restablecida correctamente." }
  }
};

export const getPublicAccessTranslations = language =>
  translations[language] || translations.pt;
